version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password19
      - POSTGRES_USER=bakery
      - POSTGRES_DB=test_bakery_db
    

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=bakery
  #     - RABBITMQ_DEFAULT_PASS=password19
  #     - deprecated_features.permit.transient_nonexcl_queues = false
